# Generated by Django 2.2.7 on 2024-05-13 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afip', '0004_storages_and_help_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigo_afip', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigo_afip', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(blank=True, max_length=70, null=True)),
                ('calle', models.CharField(blank=True, max_length=70, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('oficina', models.CharField(blank=True, max_length=10, null=True)),
                ('sector', models.CharField(blank=True, max_length=10, null=True)),
                ('torre', models.CharField(blank=True, max_length=10, null=True)),
                ('manzana', models.CharField(blank=True, max_length=10, null=True)),
                ('parcela', models.CharField(blank=True, max_length=10, null=True)),
                ('catastro', models.CharField(blank=True, max_length=10, null=True)),
                ('superficie_total', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('superficie_cubierta', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('abreviatura', models.CharField(max_length=7)),
                ('mails', models.BooleanField(default=False)),
                ('dominioweb', models.CharField(blank=True, max_length=70, null=True)),
                ('costo_mp', models.BooleanField(default=False)),
                ('cierre', models.DateField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, max_length=300, null=True)),
                ('contribuyente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='afip.TaxPayer')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.Domicilio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.TipoComunidad')),
            ],
        ),
    ]
