# Generated by Django 2.2.7 on 2024-03-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='logo',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
