# Generated by Django 2.2.4 on 2019-09-26 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0002_taxpayerextras'),
        ('mp', '0018_payment_mpid_biginteger'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='contribuyente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='afip.TaxPayer'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='mercado_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mp.Account'),
        ),
    ]
