version: '3'

services:
  mysql:
    image: mysql:8
    volumes:
      - './tmp/data:/var/lib/mysql'
    command: ["mysqld", "--innodb_force_recovery=0", "--innodb_fast_shutdown=1"]       
    ports:
      - '3306:3306'
    env_file:
      - .env

      
  api:
    build:
      context: .
    image: ghcr.io/reflejar/adminorg-api:latest
    depends_on:
      - mysql
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    links:
      - mysql
    command: python manage.py runserver 0.0.0.0:8000
