version: '3'

services:
  ddbb:
    image: postgres:10.5
    env_file:
      - .env
    ports:
      - "5432:5432"  
    volumes:
      - ./tmp:/var/lib/postgresql/data

      
  api:
    build:
      context: .
    image: ghcr.io/reflejar/adminorg-api:latest
    depends_on:
      - ddbb
    volumes:
      - ./app:/app
      - ./app/media:/app/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    links:
      - ddbb:postgres
    command: python manage.py runserver 0.0.0.0:8000
