version: '3'

services:
  postgres:
    image: postgres:10.5
    env_file:
      - .env
    ports:
      - "5432:5432"  
    volumes:
      - ./tmp:/var/lib/postgresql/data

      
  app:
    build:
      context: .
    image: ghcr.io/adminsmartlab/django:latest
    depends_on:
      - postgres
    volumes:
      - ./app:/app
      - ./media:/app/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    command: python manage.py runserver 0.0.0.0:8000
