version: '3'

services:
  ddbb:
    image: mysql:8
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

      
  api:
    build:
      context: .
    image: ghcr.io/reflejar/adminorg-api:latest
    depends_on:
      - ddbb
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    links:
      - ddbb:mysql
    command: python manage.py runserver 0.0.0.0:8000
