# Generated by Django 2.2.7 on 2020-10-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('utils', '0002_auto_20190926_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad')),
                ('exposicion', models.ManyToManyField(blank=True, to='auth.Group')),
                ('supercarpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcarpetas', to='files.Carpeta')),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos', to='files.Archivo')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad')),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
    ]
