# Generated by Django 2.2.7 on 2020-02-04 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0002_auto_20190926_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('platform_code', models.CharField(choices=[('mp', 'MercadoPago'), ('ep', 'ExpensasPagas')], max_length=5)),
                ('app_id', models.IntegerField()),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad')),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
    ]
