# Generated by Django 2.2.7 on 2021-09-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0006_auto_20210913_2135'),
        ('utils', '0001_initial'),
        ('users', '0002_auto_20210802_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.Archivo')),
                ('pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.PDF')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('client', models.CharField(max_length=300)),
                ('execute_at', models.DateTimeField(blank=True, null=True)),
                ('tried', models.PositiveSmallIntegerField(default=1)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Perfil')),
                ('attachments', models.ManyToManyField(blank=True, to='communications.Attachment')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('client', models.CharField(max_length=300)),
                ('executed_at', models.DateTimeField(auto_now=True)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Perfil')),
                ('attachments', models.ManyToManyField(blank=True, to='communications.Attachment')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
