# Generated by Django 2.2.7 on 2021-08-02 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('utils', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='exposicion',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='supercarpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcarpetas', to='files.Carpeta'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos', to='files.Carpeta'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad'),
        ),
    ]
