# Generated by Django 2.2.7 on 2021-09-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='hash',
        ),
        migrations.AddField(
            model_name='pdf',
            name='compressed',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
