# Generated by Django 2.2.7 on 2021-09-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20210913_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='compressed',
        ),
        migrations.AddField(
            model_name='pdf',
            name='ciphertext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
