# Generated by Django 2.2 on 2019-04-25 02:08

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='comunidad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='creacion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='eliminacion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modificacion',
        ),
    ]
