# Generated by Django 2.2 on 2019-05-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190425_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='es_extranjero',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
