# Generated by Django 2.2 on 2019-05-28 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190523_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='es_extranjero',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='juan', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numero_documento',
            field=models.CharField(default='3565233', max_length=13),
            preserve_default=False,
        ),
    ]
