# Generated by Django 2.2 on 2019-05-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190528_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='numero_documento',
            field=models.CharField(max_length=13),
        ),
    ]
