# Generated by Django 2.2.4 on 2019-09-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0002_taxpayerextras'),
        ('users', '0006_auto_20190528_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='afip.DocumentType'),
        ),
    ]
