# Generated by Django 2.2.6 on 2019-10-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_perfil_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion'),
        ),
    ]
