# Generated by Django 2.2.7 on 2021-09-13 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('files', '0002_auto_20210802_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('hash', models.CharField(max_length=512)),
                ('location', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad')),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
    ]
