# Generated by Django 2.2 on 2019-05-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('users', '0002_auto_20190425_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='modificacion')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad')),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Naturaleza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('naturaleza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxones', to='operative.Naturaleza')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='modificacion')),
                ('fecha', models.DateField()),
                ('fecha_indicativa', models.DateField(blank=True, null=True)),
                ('asiento', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_gracia', models.DateField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='operative.Cuenta')),
                ('vinculos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operative.Operacion')),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='modificacion')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='operative.Cuenta')),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefinicionVinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculo1', to='operative.Cuenta')),
                ('cuenta_vinculada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculo2', to='operative.Cuenta')),
                ('definicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operative.Taxon')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='naturaleza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operative.Naturaleza'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Perfil'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operative.Taxon'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operative.Titulo'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='vinculos',
            field=models.ManyToManyField(blank=True, null=True, through='operative.DefinicionVinculo', to='operative.Cuenta'),
        ),
    ]
