# Generated by Django 2.2 on 2019-05-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='vinculos',
            field=models.ManyToManyField(blank=True, through='operative.DefinicionVinculo', to='operative.Cuenta'),
        ),
    ]
