# Generated by Django 2.2.1 on 2019-05-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('operative', '0003_auto_20190515_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='modificacion')),
                ('nombre', models.CharField(max_length=80)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad')),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cuenta',
            name='metodos',
            field=models.ManyToManyField(blank=True, to='operative.Metodo'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='metodos',
            field=models.ManyToManyField(blank=True, to='operative.Metodo'),
        ),
    ]
