# Generated by Django 2.2.1 on 2019-05-30 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0004_auto_20190529_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operative.Taxon'),
        ),
    ]
