# Generated by Django 2.2.1 on 2019-06-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0002_taxpayerextras'),
        ('operative', '0005_auto_20190530_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='afip.Receipt'),
            preserve_default=False,
        ),
    ]
