# Generated by Django 2.2.1 on 2019-06-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0006_documento_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='operacion',
            name='documentos',
            field=models.ManyToManyField(related_name='operaciones', to='operative.Documento'),
        ),
    ]
