# Generated by Django 2.2.1 on 2019-06-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0007_auto_20190611_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_operacion',
            field=models.DateField(default="2018-11-11"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operacion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
