# Generated by Django 2.2.1 on 2019-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0008_auto_20190625_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodo',
            name='naturaleza',
            field=models.CharField(default='retencion', max_length=20),
            preserve_default=False,
        ),
    ]
