# Generated by Django 2.2.1 on 2019-08-01 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('operative', '0009_metodo_naturaleza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titulo',
            options={'get_latest_by': 'creacion', 'ordering': ['-creacion', '-modificacion']},
        ),
        migrations.AddField(
            model_name='titulo',
            name='comunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titulo',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha en la que fue creado.', verbose_name='creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titulo',
            name='eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='modificacion'),
        ),
        migrations.AddField(
            model_name='titulo',
            name='modificacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion'),
        ),
    ]
