# Generated by Django 2.2.4 on 2019-08-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0010_auto_20190801_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodo',
            name='base_calculo',
            field=models.IntegerField(choices=[(1, 'Diario'), (7, 'Semanal'), (15, 'Quincenal'), (30, 'Mensual'), (60, 'Bimestral'), (90, 'Trimestral'), (120, 'Semestral')], default=30),
        ),
        migrations.AddField(
            model_name='metodo',
            name='condicion',
            field=models.CharField(blank=True, choices=[(None, 'Sin condicion'), ('grupo', 'Pertenencia a un grupo')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='metodo',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='metodo',
            name='plazo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metodo',
            name='reconocimiento',
            field=models.IntegerField(choices=[(1, 'Diario'), (7, 'Semanal'), (15, 'Quincenal'), (30, 'Mensual'), (60, 'Bimestral'), (90, 'Trimestral'), (120, 'Semestral')], default=1),
        ),
        migrations.AddField(
            model_name='metodo',
            name='tipo',
            field=models.CharField(choices=[('fijo', 'Monto fijo'), ('tasa', 'Tasa')], default='tasa', max_length=15),
        ),
    ]
