# Generated by Django 2.2.4 on 2019-08-12 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('operative', '0011_auto_20190805_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.Domicilio'),
        ),
    ]
