# Generated by Django 2.2.4 on 2019-10-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0013_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='operative.Grupo'),
        ),
    ]
