# Generated by Django 2.2.6 on 2019-10-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0014_cuenta_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion'),
        ),
        migrations.AlterField(
            model_name='metodo',
            name='eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion'),
        ),
        migrations.AlterField(
            model_name='metodo',
            name='naturaleza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operative.Naturaleza'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion'),
        ),
    ]
