# Generated by Django 2.2.6 on 2019-10-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0015_auto_20191027_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodo',
            name='naturaleza',
            field=models.CharField(choices=[('interes', 'Interes'), ('descuento', 'Descuento'), ('retencion', 'Retencion')], max_length=15),
        ),
    ]
