# Generated by Django 2.2.6 on 2019-11-07 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0017_auto_20191104_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='documentos',
        ),
        migrations.AddField(
            model_name='operacion',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='operative.Documento'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='asiento',
            field=models.CharField(max_length=30),
        ),
    ]
