# Generated by Django 2.2.7 on 2019-11-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0018_auto_20191107_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_anulacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='operative.Cuenta'),
        ),
    ]
