# Generated by Django 2.2.7 on 2019-12-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0019_auto_20191129_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='afip.Receipt'),
        ),
    ]
