# Generated by Django 2.2.7 on 2020-02-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0022_cobro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobro',
            old_name='cobro_id',
            new_name='payment_id',
        ),
    ]
