# Generated by Django 2.2.7 on 2020-07-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0023_auto_20200205_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
