# Generated by Django 2.2.7 on 2020-09-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0024_operacion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titulo',
            name='supertitulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtitulos', to='operative.Titulo'),
        ),
    ]
