# Generated by Django 2.2.7 on 2020-12-03 13:12

from django.db import migrations, models
import django.db.models.deletion
import django_afip.models


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0004_storages_and_help_texts'),
        ('operative', '0025_auto_20200918_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_of_sales', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='point of sales')),
                ('document_number', models.BigIntegerField(blank=True, null=True, verbose_name='document number')),
                ('receipt_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='receipt number')),
                ('issued_date', models.DateField(verbose_name='issued date')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total amount')),
                ('net_untaxed', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total untaxable amount')),
                ('net_taxed', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total taxable amount')),
                ('exempt_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='exempt amount')),
                ('service_start', models.DateField(blank=True, null=True, verbose_name='service start date')),
                ('service_end', models.DateField(blank=True, null=True, verbose_name='service end date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='receipt expiration date')),
                ('currency_quote', models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True, verbose_name='currency quote')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_receipts', to='afip.ConceptType', verbose_name='concept')),
                ('currency', models.ForeignKey(blank=True, default=django_afip.models.first_currency, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_receipts', to='afip.CurrencyType', verbose_name='currency')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_receipts', to='afip.DocumentType', verbose_name='document type')),
                ('receipt_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='own_receipts', to='afip.ReceiptType', verbose_name='receipt type')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='receipt_afip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='afip.Receipt'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='operative.OwnReceipt'),
        ),
    ]
