# Generated by Django 2.2.7 on 2021-01-19 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0026_auto_20201203_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='predeterminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos', to='operative.Naturaleza'),
        ),
    ]
