export const receiptTypes = [
    { id: 'Factura A', nombre: 'Factura A' },
    { id: 'Nota de Credito A', nombre: 'Nota de Credito A' },
    { id: 'Nota de Debito A', nombre: 'Nota de Debito A' },
    { id: 'Factura B', nombre: 'Factura B' },
    { id: 'Nota de Credito B', nombre: 'Nota de Credito B' },
    { id: 'Nota de Debito B', nombre: 'Nota de Debito B' },
    { id: 'Factura C', nombre: 'Factura C' },
    { id: 'Nota de Credito C', nombre: 'Nota de Credito C' },
    { id: 'Nota de Debito C', nombre: 'Nota de Debito C' },
    { id: 'Factura X', nombre: 'Factura X' },
    { id: 'Nota de Credito X', nombre: 'Nota de Credito X' },
    { id: 'Nota de Debito X', nombre: 'Nota de Debito X' },
    { id: 'Liquidacion A', nombre: 'Liquidacion A' },
    { id: 'Liquidacion B', nombre: 'Liquidacion B' },
    { id: 'Orden de Pago X', nombre: 'Orden de Pago X' },
    { id: 'Retencion', nombre: 'Retencion' },
    { id: 'Transferencia', nombre: 'Transferencia' },
    { id: 'Asiento', nombre: 'Asiento' },
];
