# Generated by Django 2.2.7 on 2022-02-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20210913_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='template',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
