# Generated by Django 2.2.7 on 2020-02-04 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operative', '0021_auto_20200204_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('app_code', models.PositiveIntegerField(blank=True, null=True)),
                ('app_di', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_consorcio', models.PositiveIntegerField(blank=True, null=True)),
                ('unidad_funcional', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('importe_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('comision_plataforma', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('neto_a_depositar', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('canal_de_pago', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=90)),
                ('cpe', models.CharField(max_length=6516)),
                ('inf_deuda', models.BooleanField(default=False)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/expensas_pagas/')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_ep', to='operative.Documento')),
            ],
        ),
    ]
