# Generated by Django 2.2.7 on 2022-06-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=70)),
                ('icon', models.CharField(max_length=70)),
                ('path', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='comunidad',
            name='modulos',
            field=models.ManyToManyField(blank=True, to='utils.Modulo'),
        ),
    ]
