# Generated by Django 2.2.7 on 2024-03-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('link', models.URLField(blank=True, max_length=300, null=True)),
                ('fecha_operacion', models.DateField()),
                ('fecha_anulacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Naturaleza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('periodo', models.DateField(blank=True, null=True)),
                ('asiento', models.CharField(max_length=30)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tipo_cambio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_pesos', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OwnReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_of_sales', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='point of sales')),
                ('document_number', models.BigIntegerField(blank=True, null=True, verbose_name='document number')),
                ('receipt_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='receipt number')),
                ('issued_date', models.DateField(verbose_name='issued date')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total amount')),
                ('net_untaxed', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total untaxable amount')),
                ('net_taxed', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total taxable amount')),
                ('exempt_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='exempt amount')),
                ('service_start', models.DateField(blank=True, null=True, verbose_name='service start date')),
                ('service_end', models.DateField(blank=True, null=True, verbose_name='service end date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='receipt expiration date')),
                ('currency_quote', models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True, verbose_name='currency quote')),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('context', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
    ]
