# Generated by Django 2.2.7 on 2024-03-08 21:23

from django.db import migrations, models
import django.db.models.deletion
import django_afip.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        ('utils', '0001_initial'),
        ('afip', '0004_storages_and_help_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad'),
        ),
        migrations.AddField(
            model_name='titulo',
            name='predeterminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos', to='core.Naturaleza'),
        ),
        migrations.AddField(
            model_name='titulo',
            name='supertitulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtitulos', to='core.Titulo'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='naturaleza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxones', to='core.Naturaleza'),
        ),
        migrations.AddField(
            model_name='pdf',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad'),
        ),
        migrations.AddField(
            model_name='ownreceipt',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_receipts', to='afip.ConceptType', verbose_name='concept'),
        ),
        migrations.AddField(
            model_name='ownreceipt',
            name='currency',
            field=models.ForeignKey(blank=True, default=django_afip.models.first_currency, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_receipts', to='afip.CurrencyType', verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='ownreceipt',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='own_receipts', to='afip.DocumentType', verbose_name='document type'),
        ),
        migrations.AddField(
            model_name='ownreceipt',
            name='receipt_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='own_receipts', to='afip.ReceiptType', verbose_name='receipt type'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos', to='core.Cuenta'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='core.Cuenta'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='core.Documento'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='vinculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos', to='core.Operacion'),
        ),
        migrations.AddField(
            model_name='documento',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad'),
        ),
        migrations.AddField(
            model_name='documento',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.Cuenta'),
        ),
        migrations.AddField(
            model_name='documento',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.PDF'),
        ),
        migrations.AddField(
            model_name='documento',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='core.OwnReceipt'),
        ),
        migrations.AddField(
            model_name='documento',
            name='receipt_afip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='afip.Receipt'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.Domicilio'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='naturaleza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Naturaleza'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Perfil'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Taxon'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Titulo'),
        ),
    ]
