# Generated by Django 2.2.7 on 2024-03-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240308_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='ciphertext',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='template',
        ),
    ]
