# Generated by Django 2.2.7 on 2024-03-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240319_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
