# Generated by Django 2.2.7 on 2024-03-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comprobante_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
