# Generated by Django 2.2.7 on 2021-08-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefinicionVinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/documentos/')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_operacion', models.DateField()),
                ('fecha_anulacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('edad_limite', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_limite', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('nombre', models.CharField(max_length=80)),
                ('naturaleza', models.CharField(choices=[('interes', 'Interes'), ('descuento', 'Descuento'), ('retencion', 'Retencion')], max_length=15)),
                ('plazo', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('fijo', 'Monto fijo'), ('tasa', 'Tasa')], default='tasa', max_length=15)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reconocimiento', models.IntegerField(choices=[(1, 'Diario'), (7, 'Semanal'), (15, 'Quincenal'), (30, 'Mensual'), (60, 'Bimestral'), (90, 'Trimestral'), (120, 'Semestral')], default=1)),
                ('base_calculo', models.IntegerField(choices=[(1, 'Diario'), (7, 'Semanal'), (15, 'Quincenal'), (30, 'Mensual'), (60, 'Bimestral'), (90, 'Trimestral'), (120, 'Semestral')], default=30)),
                ('condicion', models.CharField(blank=True, choices=[(None, 'Sin condicion'), ('grupo', 'Pertenencia a un grupo')], max_length=15, null=True)),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Naturaleza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_indicativa', models.DateField(blank=True, null=True)),
                ('asiento', models.CharField(max_length=30)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_gracia', models.DateField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OwnReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_of_sales', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='point of sales')),
                ('document_number', models.BigIntegerField(blank=True, null=True, verbose_name='document number')),
                ('receipt_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='receipt number')),
                ('issued_date', models.DateField(verbose_name='issued date')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total amount')),
                ('net_untaxed', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total untaxable amount')),
                ('net_taxed', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total taxable amount')),
                ('exempt_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='exempt amount')),
                ('service_start', models.DateField(blank=True, null=True, verbose_name='service start date')),
                ('service_end', models.DateField(blank=True, null=True, verbose_name='service end date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='receipt expiration date')),
                ('currency_quote', models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=10, null=True, verbose_name='currency quote')),
            ],
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
    ]
