# Generated by Django 2.2.7 on 2021-08-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('operative', '0002_auto_20210802_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado.', verbose_name='creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado.', verbose_name='modificacion')),
                ('eliminacion', models.DateTimeField(blank=True, help_text='Fecha en la que fue eliminado.', null=True, verbose_name='eliminacion')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_indicativa', models.DateField(blank=True, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_gracia', models.DateField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Comunidad')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preoperaciones', to='operative.Cuenta')),
                ('metodos', models.ManyToManyField(blank=True, to='operative.Metodo')),
                ('vinculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos', to='operative.PreOperacion')),
            ],
            options={
                'ordering': ['-creacion', '-modificacion'],
                'get_latest_by': 'creacion',
                'abstract': False,
            },
        ),
    ]
