# Generated by Django 2.2.7 on 2021-09-03 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0003_preoperacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preoperacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='preoperacion',
            name='vinculo',
        ),
        migrations.AddField(
            model_name='preoperacion',
            name='concepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preconceptos', to='operative.Cuenta'),
        ),
    ]
