# Generated by Django 2.2.7 on 2021-09-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20210913_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='ciphertext',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
