from .titulo import Titulo
from .naturaleza import Naturaleza
from .taxon import Taxon
from .metodo import Metodo
from .grupo import Grupo
from .cuenta import Cuenta
from .cuenta import DefinicionVinculo
from .documento import Documento
from .operacion import Operacion
from .cobro import Cobro
