# Generated by Django 2.2.7 on 2022-07-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operative', '0005_auto_20210914_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='metodo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
